"""Add auto_select_tools column to sessions

Revision ID: 635d33627468
Revises: c101d202e303f4
Create Date: 2026-06-01 16:40:20.738085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '635d33627468'
down_revision: Union[str, None] = 'c101d202e303f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memory_user_id_tenant_id'), table_name='memory')
    op.alter_column('model_groups', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('models', 'api_key',
               existing_type=mysql.VARCHAR(length=1024),
               type_=src.core.encryption.EncryptedString(length=512),
               existing_nullable=False)
    op.alter_column('models', 'reasoning_effort',
               existing_type=mysql.VARCHAR(length=10),
               comment=None,
               existing_comment='DeepSeek thinking effort level (high, max); only applies when thinking_enabled is True',
               existing_nullable=True)
    op.alter_column('models', 'auto_route_eligible',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='Whether this model can be automatically selected by the intelligent router',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('rag_documents', 'content',
               existing_type=mysql.TEXT(),
               comment='Chunk text (not full document)',
               existing_nullable=False)
    op.drop_column('rag_documents', 'vector_id')
    op.add_column('sessions', sa.Column('auto_select_tools', sa.Boolean(), nullable=False))
    op.alter_column('sessions', 'auto_route_enabled',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='When True, model is auto-selected on the first user message',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('idx_sessions_title_ft'), table_name='sessions', mysql_prefix='FULLTEXT')
    op.alter_column('tool_groups', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('user_group_members', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('user_groups', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('user_groups', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_groups', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('user_groups', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('user_group_members', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('tool_groups', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.create_index(op.f('idx_sessions_title_ft'), 'sessions', ['title'], unique=False, mysql_prefix='FULLTEXT')
    op.alter_column('sessions', 'auto_route_enabled',
               existing_type=mysql.TINYINT(display_width=1),
               comment='When True, model is auto-selected on the first user message',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_column('sessions', 'auto_select_tools')
    op.add_column('rag_documents', sa.Column('vector_id', mysql.VARCHAR(length=255), nullable=True))
    op.alter_column('rag_documents', 'content',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='Chunk text (not full document)',
               existing_nullable=False)
    op.alter_column('models', 'auto_route_eligible',
               existing_type=mysql.TINYINT(display_width=1),
               comment='Whether this model can be automatically selected by the intelligent router',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('models', 'reasoning_effort',
               existing_type=mysql.VARCHAR(length=10),
               comment='DeepSeek thinking effort level (high, max); only applies when thinking_enabled is True',
               existing_nullable=True)
    op.alter_column('models', 'api_key',
               existing_type=src.core.encryption.EncryptedString(length=512),
               type_=mysql.VARCHAR(length=1024),
               existing_nullable=False)
    op.alter_column('model_groups', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.create_index(op.f('ix_memory_user_id_tenant_id'), 'memory', ['user_id', 'tenant_id'], unique=False)
    # ### end Alembic commands ###
